### ISSUE TITLE
Freezes in Windows if remote server disconnected

### ISSUE THREAD

**Issue by jerrylususu** [allanrbo/filesremote#6]
I just observed that when I shutdown a remote server, the FilesRemote program just freezes, instead of showing a dialog to indicate the connection has lost and prompt user to retry connecting. Not sure if that's the expected behavior.

**Comment by allanrbo** [comment]
Hey @jerrylususu , thanks for reporting this. Freezing UI's was actually exactly a scenario that bothered me with other solutions, motivating me to write FilesRemote, so I hope to get it right!

I was just trying it out on my Windows boks. Here's what I did:
 - Connected to a test machine.
 - Unplugged the test machine.
 - Pressed F5 for refresh
At this point in my test, the status bar in the bottom shows "Reconnecting...", and when that fails after some seconds (because I unplugged the server), it shows "Reconnecting in X seconds..." and counts down from 5 (see screenshot below). While all this is happening, the window is still what I would classify as non-frozen, as it is resizable, the top menu's are responsive, and the window responds to closing immediately.

Were you seeing a more severe kind of "freeze"? And if so, can you help describe the steps to get to it?

Thanks!
![Untitled](https://user-images.githubusercontent.com/240223/135566024-ecf1139e-6781-4c73-8630-3906f094f3e8.png)

**Comment by jerrylususu** [comment]
Thanks for your quick response! I updated to version 1.6 (running v1.5 previously) which seems to fix the problem. I tried first connect then shutdown remote machine, and there is no more freezing. I think this issue is solved.

Thanks again for your amazing work!

**Comment by allanrbo** [comment]
Only change in 1.6 was ipv6 support, so it may be by chance you are no longer seeing this. In case you see the freeze again at some point, please do let me know if you notice anything special about the steps to make it happen. Thanks!
